---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "iot-frontend-config"
  namespace: "default"
  labels:
    app: "iot-frontend"
data:
  BACKEND_HOST: "89.137.105.5"
  BACKEND_PORT: "30500"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "iot-frontend"
  namespace: "default"
  labels:
    app: "iot-frontend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "iot-frontend"
  template:
    metadata:
      labels:
        app: "iot-frontend"
    spec:
      containers:
      - name: "frontend-server"
        image: "dlxneamtu/hybrid_cloud_frontend:latest"
        env:
        - name: "BACKEND_HOST"
          valueFrom:
            configMapKeyRef:
              key: "BACKEND_HOST"
              name: "iot-frontend-config"
        - name: "BACKEND_PORT"
          valueFrom:
            configMapKeyRef:
              key: "BACKEND_PORT"
              name: "iot-frontend-config"
      - name: "nginx-srvr"
        image: "eu.gcr.io/expanded-lock-234409/nginx-srv-dneamtu:latest"
