---
apiVersion: v1
kind: Service
metadata:
  name: iot-frontend
  labels:
    app: iot-frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5061
      nodePort: 31546
  selector:
    app: iot-frontend
#    tier: rest-api-agent
  type: "NodePort"
